#! /bin/sh
feh --bg-scale ~/media/wallpapers/anime_cat_girl.jpg
$HOME/.config/polybar/launch.sh
picom -b

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width        3
bspc config window_gap          1

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Firefox desktop='^2'
bspc rule -a xfce4-terminal state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Colors
bspc config normal_border_color "#0A1f32"
bspc config active_border_color "#ce15eb"
bspc config focused_border_color "#13e881"

bspc config presel_feedback_color "#595B82"

#bspc config focus_follows_pointer true
bspc config pointer_modifier super
