#! /bin/sh
feh --bg-scale ~/media/wallpapers/kiraWallpaper.jpg
$HOME/.config/polybar/launch.sh
picom -b

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width        3
bspc config window_gap          1

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox   desktop='^2' state=monocle
bspc rule -a Alacritty desktop='^1'
bspc rule -a krita     desktop='^3'
bspc rule -a Screenkey manage=off

#Colors
bspc config normal_border_color "#000000"
bspc config active_border_color "#00ffdd"
bspc config focused_border_color "#00ffdd"

bspc config presel_feedback_color "#595B82"

#bspc config focus_follows_pointer true
bspc config pointer_modifier super
